In [ ]:
# carregar dataset
import numpy as np
import pandas as pd

dados = pd.read_csv('../../data/heart_disease.csv') 

dados.head()
dados.shape

### Análise do dataset

In [ ]:
# fazer uma copia do dataset, para trabalhar sem riscos
dados2 = pd.DataFrame.copy(dados)

In [60]:
# visualizar
dados2.head()

HeartDiseaseorAttack  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                   0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                   0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                   0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                   0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                   0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   Diabetes  PhysActivity  Fruits  ...  AnyHealthcare  NoDocbcCost  GenHlth  \
0       0.0           0.0     0.0  ...            1.0          0.0      5.0   
1       0.0           1.0     0.0  ...            0.0          1.0      3.0   
2       0.0           0.0     1.0  ...            1.0          1.0      5.0   
3       0.0           1.0     1.0  ...            1.0          0.0      2.0   
4       0.0           1.0     1.0  ...            1.0          0.0      2.0   

   MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
0      18.0      15.0       1.0  0.0   9.0        4.0     3.0  
1       0.0       0.0       0.0  0.0   7.0        6.0     1.0  
2      30.0      30.0       1.0  0.0   9.0        4.0     8.0  
3       0.0       0.0       0.0  0.0  11.0        3.0     6.0  
4       3.0       0.0       0.0  0.0  11.0        5.0     4.0  

[5 rows x 22 columns]

In [ ]:
# visualizar tipos de dados
dados2.dtypes

### Preparar para classificar

In [62]:
# Selecionar colunas relevantes para classificação
previsores = dados2.iloc[:, 1:].values  
previsores

array([[1., 1., 1., ..., 9., 4., 3.],
       [0., 0., 0., ..., 7., 6., 1.],
       [1., 1., 1., ..., 9., 4., 8.],
       ...,
       [0., 0., 1., ..., 2., 5., 2.],
       [1., 0., 1., ..., 7., 5., 1.],
       [1., 1., 1., ..., 9., 6., 2.]])

In [63]:
#definir meu alvo == target
alvo = dados2.iloc[:, 0].values
alvo

array([0., 0., 0., ..., 0., 0., 1.])

In [ ]:
dados2.describe() # visualizar para acompanhar progresso

### iniciar padronização

In [ ]:
from sklearn.preprocessing import StandardScaler # padronização

In [ ]:
# vai transformar previsores com relação a sua scscala
previsores_esc = StandardScaler().fit_transform(previsores)
previsores_esc

In [ ]:
# definir dataframe
dados3 = pd.DataFrame(previsores_esc)
dados3

In [ ]:
dados3.describe() # acompanahr progresso

In [67]:
previsores2 = dados3.iloc[:, 1:].values  
previsores2

array([[ 1.16525449,  0.19692156,  1.75793567, ...,  0.31690008,
        -1.06559465, -1.4744874 ],
       [-0.85818163, -5.07816412, -0.51180614, ..., -0.33793279,
         0.96327159, -2.44013754],
       [ 1.16525449,  0.19692156, -0.05785778, ...,  0.31690008,
        -1.06559465,  0.93963796],
       ...,
       [-0.85818163,  0.19692156, -0.05785778, ..., -1.97501498,
        -0.05116153, -1.95731247],
       [-0.85818163,  0.19692156, -0.81443838, ..., -0.33793279,
        -0.05116153, -2.44013754],
       [ 1.16525449,  0.19692156, -0.51180614, ...,  0.31690008,
         0.96327159, -1.95731247]])

In [68]:
previsores2 = pd.DataFrame(previsores2)
previsores2.head()

0         1         2         3         4         5         6   \
0  1.165254  0.196922  1.757936  1.120927 -0.205637 -0.425292 -1.762814   
1 -0.858182 -5.078164 -0.511806  1.120927 -0.205637 -0.425292  0.567275   
2  1.165254  0.196922 -0.057858 -0.892119 -0.205637 -0.425292 -1.762814   
3 -0.858182  0.196922 -0.209174 -0.892119 -0.205637 -0.425292  0.567275   
4  1.165254  0.196922 -0.663122 -0.892119 -0.205637 -0.425292  0.567275   

         7         8         9         10        11        12        13  \
0 -1.316872  0.482087 -0.244014  0.226863 -0.303173  2.329121  1.998592   
1 -1.316872 -2.074316 -0.244014 -4.407954  3.298445  0.457294 -0.429630   
2  0.759375 -2.074316 -0.244014  0.226863  3.298445  2.329121  3.617407   
3  0.759375  0.482087 -0.244014  0.226863 -0.303173 -0.478619 -0.429630   
4  0.759375  0.482087 -0.244014  0.226863 -0.303173 -0.478619 -0.024926   

         14        15        16        17        18        19  
0  1.233999  2.223615 -0.887021  0.316900 -1.065595 -1.474487  
1 -0.486592 -0.449718 -0.887021 -0.337933  0.963272 -2.440138  
2  2.954590  2.223615 -0.887021  0.316900 -1.065595  0.939638  
3 -0.486592 -0.449718 -0.887021  0.971733 -2.080028 -0.026012  
4 -0.486592 -0.449718 -0.887021  0.971733 -0.051162 -0.991662

In [69]:
# vai transformar previsores com relação a sua scscala
previsores2_esc = StandardScaler().fit_transform(previsores2)
previsores2_esc

array([[ 1.16525449,  0.19692156,  1.75793567, ...,  0.31690008,
        -1.06559465, -1.4744874 ],
       [-0.85818163, -5.07816412, -0.51180614, ..., -0.33793279,
         0.96327159, -2.44013754],
       [ 1.16525449,  0.19692156, -0.05785778, ...,  0.31690008,
        -1.06559465,  0.93963796],
       ...,
       [-0.85818163,  0.19692156, -0.05785778, ..., -1.97501498,
        -0.05116153, -1.95731247],
       [-0.85818163,  0.19692156, -0.81443838, ..., -0.33793279,
        -0.05116153, -2.44013754],
       [ 1.16525449,  0.19692156, -0.51180614, ...,  0.31690008,
         0.96327159, -1.95731247]])

In [70]:
# transformar previsores2 em dataframe
dados4 = pd.DataFrame(previsores2_esc)
dados4

0         1         2         3         4         5         6   \
0       1.165254  0.196922  1.757936  1.120927 -0.205637 -0.425292 -1.762814   
1      -0.858182 -5.078164 -0.511806  1.120927 -0.205637 -0.425292  0.567275   
2       1.165254  0.196922 -0.057858 -0.892119 -0.205637 -0.425292 -1.762814   
3      -0.858182  0.196922 -0.209174 -0.892119 -0.205637 -0.425292  0.567275   
4       1.165254  0.196922 -0.663122 -0.892119 -0.205637 -0.425292  0.567275   
...          ...       ...       ...       ...       ...       ...       ...   
253675  1.165254  0.196922  2.514516 -0.892119 -0.205637 -0.425292 -1.762814   
253676  1.165254  0.196922 -1.571019 -0.892119 -0.205637  2.439387 -1.762814   
253677 -0.858182  0.196922 -0.057858 -0.892119 -0.205637 -0.425292  0.567275   
253678 -0.858182  0.196922 -0.814438 -0.892119 -0.205637 -0.425292 -1.762814   
253679  1.165254  0.196922 -0.511806 -0.892119 -0.205637  2.439387  0.567275   

              7         8         9         10        11        12        13  \
0      -1.316872  0.482087 -0.244014  0.226863 -0.303173  2.329121  1.998592   
1      -1.316872 -2.074316 -0.244014 -4.407954  3.298445  0.457294 -0.429630   
2       0.759375 -2.074316 -0.244014  0.226863  3.298445  2.329121  3.617407   
3       0.759375  0.482087 -0.244014  0.226863 -0.303173 -0.478619 -0.429630   
4       0.759375  0.482087 -0.244014  0.226863 -0.303173 -0.478619 -0.024926   
...          ...       ...       ...       ...       ...       ...       ...   
253675  0.759375  0.482087 -0.244014  0.226863 -0.303173  0.457294 -0.429630   
253676 -1.316872 -2.074316 -0.244014  0.226863 -0.303173  1.393207 -0.429630   
253677  0.759375 -2.074316 -0.244014  0.226863 -0.303173 -1.414532 -0.429630   
253678  0.759375  0.482087 -0.244014  0.226863 -0.303173  0.457294 -0.429630   
253679  0.759375 -2.074316 -0.244014  0.226863 -0.303173 -0.478619 -0.429630   

              14        15        16        17        18        19  
0       1.233999  2.223615 -0.887021  0.316900 -1.065595 -1.474487  
1      -0.486592 -0.449718 -0.887021 -0.337933  0.963272 -2.440138  
2       2.954590  2.223615 -0.887021  0.316900 -1.065595  0.939638  
3      -0.486592 -0.449718 -0.887021  0.971733 -2.080028 -0.026012  
4      -0.486592 -0.449718 -0.887021  0.971733 -0.051162 -0.991662  
...          ...       ...       ...       ...       ...       ...  
253675  0.086938 -0.449718  1.127369 -0.992766  0.963272  0.456813  
253676 -0.486592  2.223615 -0.887021  0.971733 -3.094461 -0.991662  
253677 -0.486592 -0.449718 -0.887021 -1.975015 -0.051162 -1.957312  
253678 -0.486592 -0.449718  1.127369 -0.337933 -0.051162 -2.440138  
253679 -0.486592 -0.449718 -0.887021  0.316900  0.963272 -1.957312  

[253680 rows x 20 columns]

In [71]:
dados4.describe() # visualizar

0             1             2             3             4   \
count  2.536800e+05  2.536800e+05  2.536800e+05  2.536800e+05  2.536800e+05   
mean  -2.319179e-17  4.167800e-17 -7.618560e-18  2.688903e-17  1.322044e-17   
std    1.000002e+00  1.000002e+00  1.000002e+00  1.000002e+00  1.000002e+00   
min   -8.581816e-01 -5.078164e+00 -2.478916e+00 -8.921186e-01 -2.056365e-01   
25%   -8.581816e-01  1.969216e-01 -6.631223e-01 -8.921186e-01 -2.056365e-01   
50%   -8.581816e-01  1.969216e-01 -2.091739e-01 -8.921186e-01 -2.056365e-01   
75%    1.165254e+00  1.969216e-01  3.960906e-01  1.120927e+00 -2.056365e-01   
max    1.165254e+00  1.969216e-01  1.053427e+01  1.120927e+00  4.862949e+00   

                 5             6             7             8             9   \
count  2.536800e+05  2.536800e+05  2.536800e+05  2.536800e+05  2.536800e+05   
mean  -1.971863e-17  1.003857e-16 -3.181869e-17 -1.210007e-17 -8.133933e-17   
std    1.000002e+00  1.000002e+00  1.000002e+00  1.000002e+00  1.000002e+00   
min   -4.252922e-01 -1.762814e+00 -1.316872e+00 -2.074316e+00 -2.440141e-01   
25%   -4.252922e-01  5.672748e-01 -1.316872e+00  4.820866e-01 -2.440141e-01   
50%   -4.252922e-01  5.672748e-01  7.593754e-01  4.820866e-01 -2.440141e-01   
75%   -4.252922e-01  5.672748e-01  7.593754e-01  4.820866e-01 -2.440141e-01   
max    2.439387e+00  5.672748e-01  7.593754e-01  4.820866e-01  4.098123e+00   

                 10            11            12            13            14  \
count  2.536800e+05  2.536800e+05  2.536800e+05  2.536800e+05  2.536800e+05   
mean   3.361129e-18 -4.167800e-17  1.792602e-18  7.618560e-18  5.489845e-17   
std    1.000002e+00  1.000002e+00  1.000002e+00  1.000002e+00  1.000002e+00   
min   -4.407954e+00 -3.031731e-01 -1.414532e+00 -4.296296e-01 -4.865924e-01   
25%    2.268626e-01 -3.031731e-01 -4.786188e-01 -4.296296e-01 -4.865924e-01   
50%    2.268626e-01 -3.031731e-01 -4.786188e-01 -4.296296e-01 -4.865924e-01   
75%    2.268626e-01 -3.031731e-01  4.572943e-01 -1.598272e-01 -1.424742e-01   
max    2.268626e-01  3.298445e+00  2.329121e+00  3.617407e+00  2.954590e+00   

                 15            16            17            18            19  
count  2.536800e+05  2.536800e+05  2.536800e+05  2.536800e+05  2.536800e+05  
mean   2.554458e-17 -2.778534e-17 -5.377807e-18 -2.420013e-17 -1.434082e-17  
std    1.000002e+00  1.000002e+00  1.000002e+00  1.000002e+00  1.000002e+00  
min   -4.497181e-01 -8.870209e-01 -2.302431e+00 -4.108894e+00 -2.440138e+00  
25%   -4.497181e-01 -8.870209e-01 -6.653492e-01 -1.065595e+00 -5.088373e-01  
50%   -4.497181e-01 -8.870209e-01 -1.051636e-02 -5.116153e-02  4.568129e-01  
75%   -4.497181e-01  1.127369e+00  6.443165e-01  9.632716e-01  9.396380e-01  
max    2.223615e+00  1.127369e+00  1.626566e+00  9.632716e-01  9.396380e-01

#### Salvando

In [72]:
import pickle

In [73]:
# criar arquivo e depois atribuir var. a ele
arq1 = open('heart.pkl', 'wb')
pickle.dump(alvo,arq1)
arq2 = open('heart1.pkl', 'wb')
pickle.dump(previsores,arq2)
arq3 = open('heart2.pkl', 'wb')
pickle.dump(previsores_esc,arq3)
arq4 = open('heart3.pkl', 'wb')
pickle.dump(previsores2,arq4)
arq5 = open('heart4.pkl', 'wb')
pickle.dump(previsores2_esc,arq5)

In [74]:
# ler arquivo
arq5 = open('heart4.pkl', 'rb')

# executar 
x = pickle.load(arq5)
x

array([[ 1.16525449,  0.19692156,  1.75793567, ...,  0.31690008,
        -1.06559465, -1.4744874 ],
       [-0.85818163, -5.07816412, -0.51180614, ..., -0.33793279,
         0.96327159, -2.44013754],
       [ 1.16525449,  0.19692156, -0.05785778, ...,  0.31690008,
        -1.06559465,  0.93963796],
       ...,
       [-0.85818163,  0.19692156, -0.05785778, ..., -1.97501498,
        -0.05116153, -1.95731247],
       [-0.85818163,  0.19692156, -0.81443838, ..., -0.33793279,
        -0.05116153, -2.44013754],
       [ 1.16525449,  0.19692156, -0.51180614, ...,  0.31690008,
         0.96327159, -1.95731247]])